### ISSUE TITLE
Error on parsing integers

### ISSUE THREAD

**Issue by gokhanercan** [StarlangSoftware/TurkishMorphologicalAnalysis#2]
Test the following line with the default configurations via TestMorphologicalAnalysis, version 1.0.4 

"1 sayı tut bakalım"

Output
-----------------
1+NUM+CARD
Process finished with exit code 0

**Comment by olcaytaner** [comment]
On version 1.0.5, there is no problem.

**Comment by gokhanercan** [comment]
Working fine now. Tested with testSentence().
