### ISSUE TITLE
Self referencing hypernym relationship (TUR10-0810230)

### ISSUE THREAD

**Issue by gokhanercan** [StarlangSoftware/TurkishMorphologicalAnalysis#4]
The following synset references itself by a hypernym relationship which may cause infinite loops in hierarchical tasks. In my case, I fixed it with a self-referencing check in code. Just reporting.
turkish_wordnet.xml  v1.0.27

`
<SYNSET><ID>TUR10-0810230</ID><SYNONYM><LITERAL>üstsubay<SENSE>1</SENSE></LITERAL><LITERAL>ümera<SENSE>2</SENSE></LITERAL></SYNONYM><POS>n</POS><SR>TUR10-0815600<TYPE>DOMAIN_TOPIC</TYPE></SR><SR>TUR10-0810230<TYPE>HYPONYM</TYPE></SR><SR>TUR10-0810230<TYPE>HYPERNYM</TYPE></SR><SR>TUR10-0710260<TYPE>HYPERNYM</TYPE></SR><DEF>Binbaşı, yarbay ve albay rütbesindeki subaylara verilen genel ad|Üstsubaylar</DEF><EXAMPLE>Ordu kumandanı, kendi ümerasından birinin istediği bir matara suyu esirgedi.</EXAMPLE></SYNSET>
`

**Comment by olcaytaner** [comment]
The self-referencing data is already corrected.
